version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile_development
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/webpack-dev-server"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      # - '5000:5000'
      - '3035:3035'
      # - '3000:3000'
    env_file: production.env
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    tty: true
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db_data:
  sockets:
