version: '2'
services:
  password:
    environment:
      MYSQL_ROOT_PASSWORD: password
      # 起動時、動作しない場合は以下をコメントアウトしてからup
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      # TZ: "Asia/Tokyo"
